language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
before_install:
- pip install --upgrade setuptools
- pip install --upgrade pip
install: pip install .
script: python setup.py test
deploy:
  provider: pypi
  user: nihlaeth
  password:
    secure: LT9NLXIrLUI7ogO+3Q7kit3n739B/sMaQFoT8vXUmZF6lLjD78RyXZldo/baH7UAFAo0fBs105iA+5+dVnP2lpsWSzNQIwg4obtKCpo559tPOZZULIUKqWazeThg/NWYzZna4K737Y645cXzrl0+AMo23hmsddHJcImnTBew6EsJBTW725BhGI5jhc3tHSKfGkTW17NfZESSx624yfky+R5ASEg8FJPU3+ypW63YW05PtKfhmPxHGetUw7cB2gBUfmmhUAyXVqtbDFNdDh5RiIokDoqysAnY5AYTes/mbUKqp14sl7SyeJ95Qv3d+SOZl6g/TrLYy1SXvud6Kffb+wHd+OCfS3Dar8uaNijC2D0cESHCoihpnTBRrpyZ7SFYWvU3nlQpyfqM32VOaTGJ88zpEfzDCK8HgMaCHFUQyZCEsn09Dj3cnOvb3pysuM0DAXlH9csiqKtURMGH7pNB8lUAMdHUmHxA7fUmxyloDv7yZ680dYQ/dvvOaovIpB4UN1Kd8skBdgkMRDumfj9OtjlYMPZg2DwgVgvMTYBRPj6ZvTn52lQ/bx9vmAbum+l0iMFWoaZv6j3+HmKNNFBb4regrz7eIf4DABOuTdpQDewHoqcYTaihlUWTv9FchplHQb2VdOcYRh72lh/N8LfuBYwZ9B/ah7jLWH1ToZ9U19E=
  on:
    tags: true
  distributions: "sdist bdist_wheel --universal"
