language: python
sudo: required
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy
- pypy3
before_install:
- pip install --upgrade setuptools
- pip install --upgrade pip
install: pip install ".[deploy]"
script: python -m pytest --cov=user_config --cov-report xml -v
after_script: python-codacy-coverage -r coverage.xml
deploy:
- provider: script
  script: PYPI_REPOSITORY=testpypi sh scripts/pypi_deploy.sh
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  distributions: sdist bdist_wheel --universal
  skip_cleanup: true
- provider: script
  script: PYPI_REPOSITORY=pypi sh scripts/pypi_deploy.sh
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  distributions: sdist bdist_wheel --universal
  skip_cleanup: true
env:
  matrix:
    secure: mDTKEa4wzfc61mi16W660zf0zPqO2ydlFTZ3wFrWkB7dyV2zV9N/m/1nULKmbjHF5s9wy6urfOZXfb0XdMF0ZsYZbWHflq3lEDUYvPA6OaxM189q9fwQCkgmxtlIWSpjKM2v267gPYsbv8YZx0MvAXGbpx6xioVY7iILxl+/rsuPVyAnNJymVUhcJBY1wqoVmOFp+7hIvAn4FTCvINydcVfF/z4qu6q7Sc5LcKr39VuGZkXeUQiPzPL0HXEJMkG7MSP2LBn7PsTbgcVckWveOtatfWGq6X4K4iF9KY5bSArjw9a+LgdFZXm+dAroJ42kSaHApm5jHepUhZuBYuL4sSUGp8SLTDiRMtZ2/oL1t95+t017KZBwQciFV5L+5PKGuh3mwuz8QrqJAy6/AULMnU7dWUvBzqZg090mAaXLy9PKE2Mx9aES7iAPf1yAiDbnOQRFU0R2f3unfHYd6bc54rCNO3FWfNAjjADLuOL1EN/AvrSsmtigNFqPiC9B+Z4FkPJsEQpRN7lYv2K2W2MVXgb8nHlAGVoUeo8oFtmGPbZ4hcN6+gHe27ElRc6mTUQuPQHpMGXhou4ypZMinvnv6DsBXA6zGUwycaxiJpOSyPPXT9R8cHx34idjLmJsbbWOj02tg/BnABAMNu5p6dnaiih63JPD24ZharKd9wR5dds=
  global:
    secure: lQYqfU6rlapp7zt3VQg5HXW/kpAlRKBfsnYu3KYswjzuqk/Po/0ct7LczysQYd6scKTH/vveL4zHxfbZ04x+1YGqTDxm+vpgOCaPHUdppX6lZD4XPvudWKkj2i/ORXdGEq+vfUwe3zBXUV5mRlIx9kpLDDSUAVft6JhuhKbWrCXM9tY4L125MnyPbhW8RYOyRNMqTZ2JDfsAx0ryM1ePQSyPiBDbQbe/Mzbx+br1NBTurSRVibfITk1gZ8oyg8l4IrO3E1StR5WxoB2XE0X/IqkKepPluVEGyXgLe53rJMH7LR++yzpU3a15f/Ge1djFAzr6g6M1XS/38gkaVXn1QiwDqJDpAlwd6E+l5hnBbWnkBBixXAmuWIay1qUEa4Epfbd/ttBjOceuXc6okbgFVv0TYdu2REN63dS8EQhfVqTSJAmlpdG0IY5wFRosCBK6pPECfr7dYaqcvNVyHoO6LOjsjSV/EoQ+ZLUSHcXPKQjS7osWaugpRnDn7FCOkKrAHZaWIfPvWm7IA7M3Re08Utz7RCWNRZoNjUw5jSX/kn3o4DJVsxl9UPPzX0TB56kSyUf2+jQ8ZG4FkwOmZEXK4Ch22I4sxhvX66lD/FEhLaVEmaZyaTyMX9Vw8mvdolVFPOF0zHlh0yI5747G1LHhPE/JLccwdZtO8rCLrTXBe5o=
