language: python
sudo: required
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy
before_install:
- pip install --upgrade setuptools
- pip install --upgrade pip
install: pip install ".[deploy]"
script: python -m pytest --cov=user_config --cov-report xml -v
after_script: python-codacy-coverage -r coverage.xml
deploy:
- provider: script
  script: HOME=. TWINE_REPOSITORY=testpypi sh scripts/pypi_deploy.sh
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  skip_cleanup: true
- provider: script
  script: HOME=. TWINE_REPOSITORY=pypi sh scripts/pypi_deploy.sh
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  skip_cleanup: true
env:
  global:
  - TWINE_USERNAME=nihlaeth
  - secure: PtRnzrIxkCArugy5dYr55RwxWq7X/UUc0wIGOvZn5C7ZiDNL0G3SrQxLffGzto3S0Qdk1h6W0tNyLuBZ0izUo64iRH2yhfQdABTHt6hLo1z5lCDF11J0gAkCMtFhpRfseueC4SkBO01cBqLlkvoR4mJaCTDQlOPmUUf9JWusemLVYRdqvL3+o6fPo3eSrqBrPqdBkCjpzk258Z3Lt86zodu9ywv4ffKJC7gt7KKx4j/RbFFau9Qp/EAfQqcdbhVEUe7YXdam37CrPO87jW/ZoAaDucwooot9CrqQ2+5OBkpUfP0vbbI3o3XgQ683yeR2D7cHCrmtEoUnlhHgvgdRhRvaPChmlXhxIGWLr/LvydVuFSkXLPM093MDd+tIp9c2lv/yi81+4TDpncBnujKnEOkfYIU+hRaP2Ip7tZiDp+Jn4C+z79YCx9gRaqYsIswisv+1L1TfaYqa987eHw9CsiCVdtee+eus5WxOFQyyUbMyy2uEUA7jEucZLMVbIEg52BI8YlLTkmaJ3iVki8Hg+GosDqQXMlZEvJOxoTdMeY5YIc4w3jrSOFCvfLNv4119ZcOGYm/AhzfXUZFqhEicK9DCcWkrGfq9OjBzpVvfqmIJ+fT+9QVhA7UzDgLmox9EZUT+KbCUTwg2mqYr/efXPgK2G1oq4SOvzpik6PlvCWs=
  - secure: mDTKEa4wzfc61mi16W660zf0zPqO2ydlFTZ3wFrWkB7dyV2zV9N/m/1nULKmbjHF5s9wy6urfOZXfb0XdMF0ZsYZbWHflq3lEDUYvPA6OaxM189q9fwQCkgmxtlIWSpjKM2v267gPYsbv8YZx0MvAXGbpx6xioVY7iILxl+/rsuPVyAnNJymVUhcJBY1wqoVmOFp+7hIvAn4FTCvINydcVfF/z4qu6q7Sc5LcKr39VuGZkXeUQiPzPL0HXEJMkG7MSP2LBn7PsTbgcVckWveOtatfWGq6X4K4iF9KY5bSArjw9a+LgdFZXm+dAroJ42kSaHApm5jHepUhZuBYuL4sSUGp8SLTDiRMtZ2/oL1t95+t017KZBwQciFV5L+5PKGuh3mwuz8QrqJAy6/AULMnU7dWUvBzqZg090mAaXLy9PKE2Mx9aES7iAPf1yAiDbnOQRFU0R2f3unfHYd6bc54rCNO3FWfNAjjADLuOL1EN/AvrSsmtigNFqPiC9B+Z4FkPJsEQpRN7lYv2K2W2MVXgb8nHlAGVoUeo8oFtmGPbZ4hcN6+gHe27ElRc6mTUQuPQHpMGXhou4ypZMinvnv6DsBXA6zGUwycaxiJpOSyPPXT9R8cHx34idjLmJsbbWOj02tg/BnABAMNu5p6dnaiih63JPD24ZharKd9wR5dds=
