language: python
sudo: required
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy
before_install:
- pip install --upgrade setuptools
- pip install --upgrade pip
install: pip install ".[deploy]"
script: python -m pytest --cov=user_config --cov-report xml -v
after_script: python-codacy-coverage -r coverage.xml
deploy:
- provider: script
  script: HOME=. PYPI_REPOSITORY=testpypi sh scripts/pypi_deploy.sh
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  distributions: sdist bdist_wheel --universal
  skip_cleanup: true
- provider: script
  script: HOME=. PYPI_REPOSITORY=pypi sh scripts/pypi_deploy.sh
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  distributions: sdist bdist_wheel --universal
  skip_cleanup: true
env:
  matrix:
    secure: mDTKEa4wzfc61mi16W660zf0zPqO2ydlFTZ3wFrWkB7dyV2zV9N/m/1nULKmbjHF5s9wy6urfOZXfb0XdMF0ZsYZbWHflq3lEDUYvPA6OaxM189q9fwQCkgmxtlIWSpjKM2v267gPYsbv8YZx0MvAXGbpx6xioVY7iILxl+/rsuPVyAnNJymVUhcJBY1wqoVmOFp+7hIvAn4FTCvINydcVfF/z4qu6q7Sc5LcKr39VuGZkXeUQiPzPL0HXEJMkG7MSP2LBn7PsTbgcVckWveOtatfWGq6X4K4iF9KY5bSArjw9a+LgdFZXm+dAroJ42kSaHApm5jHepUhZuBYuL4sSUGp8SLTDiRMtZ2/oL1t95+t017KZBwQciFV5L+5PKGuh3mwuz8QrqJAy6/AULMnU7dWUvBzqZg090mAaXLy9PKE2Mx9aES7iAPf1yAiDbnOQRFU0R2f3unfHYd6bc54rCNO3FWfNAjjADLuOL1EN/AvrSsmtigNFqPiC9B+Z4FkPJsEQpRN7lYv2K2W2MVXgb8nHlAGVoUeo8oFtmGPbZ4hcN6+gHe27ElRc6mTUQuPQHpMGXhou4ypZMinvnv6DsBXA6zGUwycaxiJpOSyPPXT9R8cHx34idjLmJsbbWOj02tg/BnABAMNu5p6dnaiih63JPD24ZharKd9wR5dds=
  global:
    secure: JON/SjprSM1TtpOPei+KMHEVVipmmSnjwuv9gvw4byYgkfGYF6+oqgeN+NmH+B2P3cfnEGAsEBVNSQsk8P6LPS147Xj+G//Ezobjdjk7TMVcrizA8qEtxqaUCkX2r8lJ5PN00y7eZDPi/osoJ0eLw8whrAfaAqzLGHpzF2tJj10s3ykT4iAVK219AUYY2kE5ewOWYt/e7ZiYk7BVGGUvw0yUu1XWC+Wuh9TQZvLE+BhafNN6k4q/bcdnh9SH3s+eNJ3WFLF7+vM2/HsiZV1qIAciYzPYk4Dkugri9RHcAq4CciaWcyyjyy8kK7t2v1cxUNFVSKnrzBy95FRYOqUNTesaaxtlVJ/1M/YrXJQyvD0lm8Torxk1Yk0+PEIt+4NmORpjtMGZOxO7L+un6TY6wlEJM0g2Jh8X+Lzs4j8qSkD0dTAYcbkH0BrtRZchGj2O8f281/UZPlZiuRPiz9vCsSYASBH3DYEuWKSIzS7gW2/uTtwJ4qKoXRJk3I/8g5lu8PI2B0dKeI5BYnb02l4wsbi4xl2c+uouqGCL6qyVqXjb5c6xQiVgxqpEhP0KlKPiQhSQ5e5wrCvYpBE0BKW/6QWolLii/OSY5o63db63mWXtL+p6zYadkOd13XgOTNI/Eiyi7ceAD6bpYm+PdsEFJsKEVeFK0zmth2ltl5mhCIA=
